export const TOGGLE_HAMBURGUER_HIDDEN = "TOGGLE_HAMBURGUER_HIDDEN";
export const TOGGLE_HAMBURGUER_HIDDENCHAT = "TOGGLE_HAMBURGUER_HIDDENCHAT";

export const toggleHamburguerHidden = () => ({
  type: TOGGLE_HAMBURGUER_HIDDEN,
});
